[project]
name = "movie-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "mcp>=1.5.0",
    "mcp-server-fetch>=2025.1.17",
    "python-dotenv>=1.1.0",
]
